= Entries 115-120

Johanna Martha Maria
geb. den 16. August 1874, getauft 23. August 1874.
Eltern Heinrich Rücklos, und Friederick, geb.
Pathele: Frau Johanna Ebel und Frau
feiern
N. Cammerer-Pastor.
15.
.
Henriette Christine Mathilde
.
geb. den 19. Nov 1874. get. den 29. Nov. 1874
Eltern: Ludwig Köldewey u. dessen Ehefrau Sophia.
Pathen:
1875.
.
Carmeren
"
./.
kosten.
135.
Kermmann Wilhelm Ferdinand
.
Sohn von:
Ferdinand und Maria Reinking
geboren den 21ten Januar 1875 getauft den 31. Jan, 75.
Taufpathen: Herrmann Brinking
Wilhelm Glocke w.
einreichbärke.
. 4
(abgemeres.)
Pieser
136.
Nophia Emilia
Vorher von
Friedrich Joch und Sorge verhältnere
geb. an §. 11. 6. 1775 eine getötiges den 5. d. M. O.
Baufpathen. Doris Haupt und Cristine Wättzier
* *
27
E. Lammerer.
Päster
Hermann, Heinrich Wilhelm
+ the
Sohn von Carl Grote und Corcline, geb. Kruckeberg
13
geboren den 7. April 1875, getauft den 11. April 1865.
Pathen: Heinrich Krückeberg und W. Keinking. W. Grote
Chr. Schemerloh Vice-Rath
1876.
X. H. Kammerka
stehen.
138.
Johann Christian Ferdinand Hugo
6. Thait?
Sohn von Aug. HugöCaemmerer u. Margaretha, geb. Beck,
geboren den 10. März 1876. getauft den 12. Márz
Pathen: Johann Ebel, Christian Blecke and
Ferdinand Reinking.
A. H. Caemere
.
