= Entries 91-96

109
ich Wilhelm
geboren den 13 Juli, u. get. den 23 Juli 1871.
Wilhelm Fells
Eltern.
Elisabeth, geb. Rup.
Pathen: Christian Bleeke u. Conrad Fells.
110,
Ludwig Clemens
geb: den 7 August 1869 u. get: den 30 Juli 1871.
(Johann Krohn)
Eltern Veronica, geb. Vox.
Pathen: Heinrich Rücklas.
111
ndreas Friedrich August
einem kommen wurde.
geb. den 31 August u. get. den 10 Sept. 1871.
(Friedr. August Haupt.
Eltern:
Louise Maria Magdel. Dous geb. Daniel,
Pathen: Andreas Thieme u. Friedr. Habermann.
112,
Sophia Louise
geb: den 1sten Dez. u. get. den 17 Dezemb. 1871.
(Heinrich Heier)
Eltern
Isabella, geb. Biebelheimer,
Pathen Sophia Grote und Louise Reinking.
113,
Ern
dinand
A Friedrich P
und
geb. den 23 Februar u. gut: den 3 März 1872.
(Friedrich Blecke
Eltern:
Maria, geb. Biebelheimer,
Pathen: Ferdinand Reinking, Heinrich Heier, Ernst Scheumann.
114,
Emilie
rolin
M
in
7 6.
geb. den 4ten u. get. den 10 Maerz 1872.
(Andreas Thieme
Eltern: L Sophia, geb. Klein
Pathen. Emilie Thieme u. Carolina
Grote
95
