= Entries 85-90
.D
1871
ein
Mein
4 s/12
Heinrich Friedrich Wilhelm
103,
geboren den 21 September u. getauft den 2 October 1870
(Ludwig Kaldeney u.
Eltern Jakkia, geb. Cordes
Pathen: Friedrich Thiele u. Wilhelm Engelbrecht
tea Christina Paulina.
104.
Doie
.
geb: den 3 October und art. den 9ten October 1870.
(Gottfried Thieme)
Eltern:
Amalia, geb.
Pothen: Darothea Haugh u. Christina Büttner.
Clara Maria
165.
geb: den 1. Januar u. get. den 8ten Januari 1871.
Andreas Thieme
Eltern
Sophia, geb. Klein
Pohen: Amalia Thieme u. Carolina Schamerloh.
Einand
Friedrich Fe
106
3
nimmig
geb: den 12. Februar u. get. den 26 Febuar 1871.
Eltern.  [Hanrich Rucklos]
Friedricka, geb. Dauner
Pathen: Friedrich Bleeke u. Ferdinand Reinking.
Sophia Christi
107
gelegten mich.
Wilhelm Eduard
geb. den 22 Februar u. get. den 5 März 1871.
geb. den 6. April 1841.
Consed Falls
Eltern
get. den 15. Apr. 21.
Carolina, geb. Feldner.
Eltern: Ch. Blecke, Maria
Pathen: Sophia Thience u. Christina Büttner
Pathen H. Plectle
Rup
Ed. Heckmann
Anna Maria Sophia
108,
get; durch P. Rupprecht
geb: den 26 Maerz u. get. den 9te April 1871.
eingetragen von St. G.
Eltern L. Wilhelm Schamerloh
Philippine, geb. Kruckeberg
Pathen: Maria Bleeke, Sophia Grote.
