= Entries 127-132

Emma Maria Christine
Tochter von Hermann Büttner und das. Frau Louise
geb. 25. Feb. 1877 gekauft 28. Feb 1877.
Pathen: Emma Obel, Minna Kunge.
A. H. Cämmerk
Adeline Sophia Elisabeth
açon de ce qu'il
Tochter von Hermann Reinking u. d. h. Fr. Maria
geb. den 16. März 1877. getauft den 25. Merz 1874.
Pathen: Sophie Holle, Sophie Heckmann,
Elisabeth Jäbker.
*
H. Cämmerer
Carl Friedrich Heinrich
.
Sohn von Carl Krückeberg und das Frau Caroline.
geb. 28. Maix 1877. getauft den 2. April 1877
Pathen. Heinrich Krückeberg, H. Grote, F. Weyland.
A. U. Caemerer.
Clara Louis Margaretha
Tochter von Verdinand Reinking und einer
deren Maria geworend Bäcke, geboren den 31. März
1878, getauft den 1. April 1828
Pathen: Louise Blocke
Elise Bliche, Margarethe Cammeser
A. K. Caeninerer
Therese Emilie Sophie
29.6.44
Frau
Tichter von August Haupt u. dessen
Döris geb.
Dauel, geb: den 11 Decemb. u. get: den 22t Decembr. 1878.
Pathen: Thierse Roth u. Sophie Thienen.
Heinrich Wilhelm
Sohn von Friedrich Roth und seiner Ehefrau Thäuse, geb. Bütten,
geboren den 18. August, und getauft dem 8. Septr. 1878.
Pathen: Heinrich Büttner und
Wilhelm Weyland.
A. H.
Cammerer
Pestor.
Elise Emeline,
Tochter von H. Heier und dessen Ehefrau Isabella, geb. Bibelheimer.
1878. Pathen.
geboren den 23. Sept. 1878 und getauft am 6. Oct.
Caroline Grote, Caroline Nürgen, und Maria Stindler.
