= Enties 121-126
Johann Heinrich Friedrich,
139.
Sohn von: H. Heier und Isabelle geb. Bibelhaimer.
geboren den 4. März und getauft den 12. Mörz 1876.
Pathen: Pohn Ehrmann, Heinrich Krückeberg,
und Friedrich Weiland.
A. H. Caemerer,
Pastor.
Otto konst.
140.
Sohn von Chr. Blecke u. Maria geb. Rup.
geboren den 2. April 1876 den 25. März 1876,
H. Krückeberg
getauft den 2. April 1876. Pathen.
Kammerer
A.W.
und W. Reinking.
Pesser
Mathilda Amalie Christine.
141
Vor Herr
Tochter von W. Schamerloh u. Philippine geb.
Krückeberg, geboren den 21. April
1876, und getauft
den 30 April 1876. Pothen: Christine Büttner u.
Amalia Thierne.
de
1.
Cammerer
142.
Meilen
Heinrich Hermann
Sohn von W. Fells u. Elisabeth geb. Rup-
I
geboren den 24. Mai 1876. gekauft den 28.Mai 1876
Pathen: Heinrich Blicke u. Hermann Reinking.
P. H. Wammerer
kosten.
143
Heinrich Andreas
Ehefrau
Sophie,
Sohn von Andreas Thienen und dessen
geboren den 21. Juli 1876. getauft den
22. July. 1876.
Pathen Heinrich Bischoff, Heinrich Grote,
A. H. Caunerer
Pfarrer
144.
Johanna Sophia.
*
Tochter von W. Holle und Sophia, geb. Blecke
geboren den 6. August 1876, getauft den 20 August
seethen: Louise Holle, Maria Bleckl
Christine
26.
Calinerer
at
Heckmann
kührer
145.
Friedrich Gottlob Wilhelm
Söpe von August Haupt u. d. h. Ehefrau Dorib
geb. 6. Sept. 1876, get. 10. Sept 1876.
Gottl Büthner
Pathen: Friedrich Thieme
U. Egermeister v. M.
