= Immanuel Lutheran Kirchenbuch

== Timeline

Using the dates and events described in the https://immanueldecatur.org/Church_History.html[brief history of Immanuel Lutheran Church], Decatur, Indiana,
we can contruct this timeline:

- 1838
+
Johnann Heinrich Philip Bleeke(JHP Bleeke), then living at Cincinnati,
made a trip to Adams County and for his future home bought the northwest quarter
of section 21, being the third man to enter a deed for land in what is now Union Township.

NOTE: The purchase was completed until ...todo: xref to NARA land records.

- 1840
+
JHP Bleeke returned with his wife and their two sons and three daughters,
arriving on November 27. The wagon-cover stretched across crotchet-poles was
their only shelter while they built a rough log-house, which still had no
roof or floor when they moved in on December 24.

- 1849
+
The Rev. J. Andreas Fritze, Pastor of St. John’s Bingen and
of St. Peter’s Root Township, began holding regular preaching services in the Bleeke
home.

- 1849 November
+
Two other families arrived from Germany to
settle in Union Township:  John H. Krueckeberg with his wife and three daughters;
and Henry Wm. Weyland and his wife, son, and daughter.  Both families at once joined
the Bleekes at divine services in their home, thus forming the nucleus of the present
Immanuel Lutheran congregation.

- 1852
+
JHP Bleeke family buids the house that still stands on the old home place.

During the first years in their new home, the Bleekes would walk five miles
through the swampy woods to attend church services in the Clamor Fuelling home
in Root Township and then in the log church built there in the early 1840s.

Other Lutheran pioneers were J.H.W. Carl Grote, who came in 1852; C.D. Ferdinand
Reinking in 1853; J. Andreas Thieme in 1855; and Carl H.W. Krueckeberg,
C. William Schamerloh, K.H. Ludwig Koldewey, J.F. Hoeriger, and H.J. Ruecklos, Sr.,
all before the end of 1858.

These ten men, with John Bleeke and his sons Christian F. and Karl F. Wm., were
charter members who on December 14, 1858, adopted and signed the
constitution and thus formally organized Immanuel Lutheran Church.

- 1851
+
The first church, built of logs, was begun in 1851 by the half dozen pioneers here
at the time, but the structure was completed and dedicated in 1855. The first
parsonage was constructed in 1865 and was replaced in 1917 with a brick-veneer
building. The present house of worship was built in 1891 at
a cost of about $5000.  In 1912, the church was placed on a higher foundation,
furnace and pipe organ installed, the tower lowered 30 feet, and other minor changes
made.  In 1929, side balconies were built, the church redecorated, and the altar statues
of Christ and the adoring angels added.

== Church Registry Suggested Table of Contents

Table of Contents

* image images 1 Book Cover

* image images 3 Title Page Kirchenbuch … Imanuels Gemeinde

* images 4-10 Kirchen Ordnung

* images 11 Resolution Regarding Fees for New Members

* images 12-16 Signees of the Church Constitution, 14 Dec 1858

first was Johann HP Bleeke, then his son Christian Friedrich, then John H Krückeberg

* images 18-36 Immanuel Church Biographies

* images 37 Pastors of the Congregation, 1865-1950

* images 38-44 Registry of Members or Voters

* images 46-115 Baptisms, with parents & sponsors. Last is Gretchen Mathilda Bleeke, baptized images 9 July 1905
	 	 Gretchen was grandmother of Steve & Todd

* images 116-125 Registry of Confirmands, 1867-1905

* images 126-195 Registry of Communicants

* images 196-205 Marriages

* images 206-228 appears to be a Record of Participation in Voting, e.g. present or absent

* images 229-241 Death Registry

* images 242 Back Cover

NOTE: Page 38 (two marriages from 1905) was out of place. Page 38 needs to be
moved into position 205. After you make this adjustment, the page numbers shown
in the "table of contents" should be correct.:
